server:
  port: 8003
spring:
  application:
    name: users
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
feign:
  client:
    config:
      default:
        connectionTimeout: 5000     #配置所有服务连接超时
        readTimeout: 5000           #配置所有服务等待超时
        loggerLevel: full             #全局开启服务日志展示
logging:
  level:
    com.dream.clients: debug
